### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by floion**

### CODE REVIEW

**Comment by floion** [comment]
@balena-ci I self-certify!

**Comment by acostach** [comment]
Hi @stathismor , bulldozer seems to no longer take into account the versionbot/pr-draft labels and merges PRs as soon as the checks pass. Is this intentional?

**Comment by stathismor** [comment]
What do you mean @acostach ? It should only merge when all required checks pass. I see a pending PR here where it respects that https://github.com/balena-os/balena-variscite/pull/146

**Comment by acostach** [comment]
Hi @stathismor if we look up in the history we see that the PR was approved, then the **pr-draft** label was added, and some time afterwards bulldozer merged it although it still had the pr-draft label:

[versionbot3](https://github.com/apps/versionbot3) bot approved these changes 2 days ago
[floion](https://github.com/floion) added the versionbot/pr-draft label [2 days ago](https://github.com/balena-os/balena-variscite/pull/149#event-6419635733)[](https://github.com/floion)
@[floion](https://github.com/floion)[](https://github.com/apps/bulldozer-balena) floion force-pushed the various_improvements branch from ed86941 to 7aa573f
2 days ago
@[bulldozer-balena](https://github.com/apps/bulldozer-balena) bulldozer-balena bot merged commit [583cc6e](https://github.com/balena-os/balena-variscite/commit/583cc6e16c47c8a6ba6f9b7a194386500200dcf0) into master [2 days ago](https://github.com/balena-os/balena-variscite/pull/149#event-6419830285)
6 checks passed

The PR https://github.com/balena-os/balena-variscite/pull/146 you mention does not have the draft label added. Until now the versionbot/pr-draft label used to prevent vb from automatically merging PRs.

**Comment by stathismor** [comment]
Oh, I see, you're focusing on draft PRs! I don't know about the label you mentioned @acostach , I know bulldozer should respect the GitHub draft I believe, not that label. I see that the description of the label says "do not merge automatically" but maybe it's an obsolete label/feature? If the PR was actually converted to a draft one, it should not have been merged.

**Pull request merged**
