### PR TITLE
Thud update

### PR DESCRIPTION
**Pull request by vicgal**
Update balena-varisicite to thud

### CODE REVIEW

**Comment by vicgal** [comment]
> The poky thud tags I see are:
> 
> `thud-20.0.0`, `thud-20.0.1`, `thud-20.0.2`, and `thud-20.0.3`
> 
> Are you sure `thud-20.0.3-4-ge694933647` is a valid tag?

I did a `git describe --tags` which enabled matching a lightweight (non-annotated) tag. I think the base tag is `thud-20.0.3`. Or if you think I should use some other method to list the tag of the current branch?

**Comment by floion** [comment]
@vicgal was this updated as per the comments?

**Comment by vicgal** [comment]
> @vicgal was this updated as per the comments?

yes, did the update

**Comment by vicgal** [comment]
> This PR also needs to set the yocto version to thud in the .coffee files

Updated and pushed again

**Pull request merged**
